services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: himalaya_username
      POSTGRES_PASSWORD: himalaya_password
      POSTGRES_DB: himalaya_database
    volumes:
      - himalaya-data:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  himalaya-data:
